-- Add missing columns to News
ALTER TABLE "News" ADD COLUMN IF NOT EXISTS "category" TEXT DEFAULT 'Général';
ALTER TABLE "News" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN DEFAULT false;
ALTER TABLE "News" ADD COLUMN IF NOT EXISTS "isCopyProtected" BOOLEAN DEFAULT false;

-- Add missing columns to ShopProduct
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "isNew" BOOLEAN DEFAULT false;
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "gallery" TEXT[] DEFAULT '{}';
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "features" TEXT[] DEFAULT '{}';
ALTER TABLE "ShopProduct" ADD COLUMN IF NOT EXISTS "specifications" JSONB DEFAULT '{}';

-- Add missing columns to Seed
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "availability" TEXT DEFAULT 'En stock';
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "careInstructions" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "diseases" TEXT[] DEFAULT '{}';
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "features" TEXT[] DEFAULT '{}';
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "fertilizer" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "fullDescription" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "germination" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "harvestTime" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "moisture" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "origin" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "packaging" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "plantingDepth" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "plantingInstructions" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "purity" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "soilType" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "spacing" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "totalReviews" INTEGER DEFAULT 0;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "unit" TEXT DEFAULT 'kg';
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "variety" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "watering" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "yield" TEXT;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN DEFAULT false;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "isCopyProtected" BOOLEAN DEFAULT false;
ALTER TABLE "Seed" ADD COLUMN IF NOT EXISTS "gallery" TEXT[] DEFAULT '{}';
