/* eslint-disable no-console */
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const seeds = [
  {
    slug: 'mais-hybride-precoce',
    name: 'Maïs hybride précoce',
    description: "Variété hybride à cycle court, adaptée aux zones à saison des pluies réduite.",
    fullDescription:
      "Ce maïs hybride précoce arrive à maturité en moins de 90 jours, ce qui en fait un excellent choix pour les zones où la saison des pluies est courte ou irrégulière. Rendement élevé et bonne résistance à la sécheresse en fin de cycle.",
    price: 3500,
    stock: 250,
    unit: 'kg',
    category: 'Céréales',
    variety: 'Hybride F1',
    origin: 'Côte d\'Ivoire',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '90-95%',
    harvestTime: '85-90 jours',
    plantingDepth: '3-5 cm',
    spacing: '75 cm x 25 cm',
    soilType: 'Sol limoneux, bien drainé',
    watering: 'Modéré, sensible à l\'excès d\'eau en début de cycle',
    yield: '5-7 tonnes/hectare',
    features: ['Cycle court', 'Résistant à la sécheresse', 'Haut rendement'],
    diseases: ['Résistant à la rouille commune'],
    isFeatured: true,
    isPublished: true,
  },
  {
    slug: 'riz-nerica-4',
    name: 'Riz NERICA 4',
    description: "Riz pluvial issu du croisement riz africain/riz asiatique, adapté aux plateaux.",
    fullDescription:
      "Le NERICA 4 combine la rusticité des variétés africaines et le potentiel de rendement des variétés asiatiques. Cultivable en riziculture pluviale de plateau, sans besoin d'irrigation permanente.",
    price: 4200,
    stock: 180,
    unit: 'kg',
    category: 'Céréales',
    variety: 'NERICA 4',
    origin: 'Afrique de l\'Ouest',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '85-90%',
    harvestTime: '100-110 jours',
    plantingDepth: '2-3 cm',
    spacing: '20 cm x 20 cm',
    soilType: 'Sol de plateau, drainé',
    watering: 'Pluvial, pas d\'irrigation permanente requise',
    yield: '2.5-4 tonnes/hectare',
    features: ['Culture pluviale', 'Cycle court', 'Bonne tolérance à la sécheresse'],
    diseases: ['Tolérant à la pyriculariose'],
    isFeatured: true,
    isPublished: true,
  },
  {
    slug: 'tomate-resistante-fletrissement',
    name: 'Tomate résistante au flétrissement bactérien',
    description: "Variété de tomate sélectionnée pour sa résistance aux maladies bactériennes courantes.",
    fullDescription:
      "Variété maraîchère à fruits fermes, adaptée à la culture en saison chaude et humide. Sa résistance au flétrissement bactérien réduit fortement les pertes en zone tropicale.",
    price: 2800,
    stock: 320,
    unit: 'sachet (500 graines)',
    category: 'Maraîchage',
    variety: 'Résistante F1',
    origin: 'Cameroun',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '88-92%',
    harvestTime: '70-80 jours',
    plantingDepth: '1 cm',
    spacing: '50 cm x 50 cm',
    soilType: 'Sol riche en matière organique, bien drainé',
    watering: 'Régulier, éviter l\'excès sur le feuillage',
    yield: '25-35 tonnes/hectare',
    features: ['Résistante aux maladies', 'Fruits fermes', 'Bonne conservation'],
    diseases: ['Résistante au flétrissement bactérien (Ralstonia)'],
    isFeatured: false,
    isPublished: true,
  },
  {
    slug: 'niebe-cornille',
    name: 'Niébé (haricot cornille)',
    description: "Légumineuse rustique, riche en protéines, adaptée aux zones semi-arides.",
    fullDescription:
      "Le niébé est une culture vivrière essentielle en zone sahélienne : rusticité, fixation d'azote dans le sol et forte valeur nutritionnelle. Cette variété est sélectionnée pour son rendement en grain et en fourrage.",
    price: 2200,
    stock: 400,
    unit: 'kg',
    category: 'Légumineuses',
    variety: 'Locale améliorée',
    origin: 'Sahel',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '90%',
    harvestTime: '60-70 jours',
    plantingDepth: '3-4 cm',
    spacing: '40 cm x 20 cm',
    soilType: 'Sol sableux à limoneux, tolère les sols pauvres',
    watering: 'Faible, très tolérant à la sécheresse',
    yield: '1-1.5 tonnes/hectare',
    features: ['Fixe l\'azote dans le sol', 'Très résistant à la sécheresse', 'Riche en protéines'],
    diseases: [],
    isFeatured: false,
    isPublished: true,
  },
  {
    slug: 'manioc-tme-419',
    name: 'Manioc TME 419',
    description: "Variété de manioc à haut rendement, tolérante à la mosaïque africaine.",
    fullDescription:
      "Boutures de manioc TME 419, largement diffusées en Afrique de l'Ouest et du Centre pour leur tolérance à la mosaïque africaine du manioc et leur bon rendement en racines.",
    price: 5000,
    stock: 150,
    unit: 'lot de 50 boutures',
    category: 'Tubercules',
    variety: 'TME 419',
    origin: 'Nigeria',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: 'N/A (bouturage)',
    harvestTime: '10-12 mois',
    plantingDepth: '10-15 cm (bouture inclinée)',
    spacing: '1 m x 1 m',
    soilType: 'Sol léger, bien drainé',
    watering: 'Faible à modéré',
    yield: '20-25 tonnes/hectare',
    features: ['Tolérant à la mosaïque africaine', 'Haut rendement en racines', 'Bonne teneur en amidon'],
    diseases: ['Tolérant à la mosaïque africaine du manioc (CMD)'],
    isFeatured: true,
    isPublished: true,
  },
  {
    slug: 'arachide-fleur11',
    name: 'Arachide Fleur 11',
    description: "Variété d'arachide à cycle court, très cultivée en Afrique de l'Ouest.",
    fullDescription:
      "Fleur 11 est une variété d'arachide de référence en Afrique de l'Ouest, appréciée pour son cycle court et sa bonne teneur en huile. Adaptée aux zones à pluviométrie moyenne.",
    price: 3000,
    stock: 280,
    unit: 'kg',
    category: 'Oléagineux',
    variety: 'Fleur 11',
    origin: 'Sénégal',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '85%',
    harvestTime: '90-100 jours',
    plantingDepth: '5 cm',
    spacing: '50 cm x 15 cm',
    soilType: 'Sol sableux, bien drainé',
    watering: 'Modéré',
    yield: '1.2-1.8 tonnes/hectare',
    features: ['Cycle court', 'Bonne teneur en huile', 'Adaptée à la culture pluviale'],
    diseases: [],
    isFeatured: false,
    isPublished: true,
  },
  {
    slug: 'piment-yolo-wonder',
    name: 'Piment Yolo Wonder',
    description: "Piment doux à gros fruits, très demandé sur les marchés locaux.",
    fullDescription:
      "Le Yolo Wonder produit de gros fruits charnus, verts virant au rouge à maturité. Variété productive, appréciée pour sa saveur douce et sa bonne tenue après récolte.",
    price: 2500,
    stock: 200,
    unit: 'sachet (200 graines)',
    category: 'Maraîchage',
    variety: 'Yolo Wonder',
    origin: 'Cameroun',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '85-90%',
    harvestTime: '75-85 jours',
    plantingDepth: '1 cm',
    spacing: '45 cm x 45 cm',
    soilType: 'Sol riche, bien drainé',
    watering: 'Régulier',
    yield: '15-20 tonnes/hectare',
    features: ['Gros fruits', 'Saveur douce', 'Bonne conservation'],
    diseases: [],
    isFeatured: false,
    isPublished: true,
  },
  {
    slug: 'oignon-violet-galmi',
    name: 'Oignon violet de Galmi',
    description: "Variété d'oignon locale très prisée, à bulbes violets et saveur relevée.",
    fullDescription:
      "L'oignon violet de Galmi est une variété de référence en Afrique de l'Ouest, reconnue pour sa bonne conservation et sa saveur prononcée. Adapté à la culture en saison sèche avec irrigation.",
    price: 3200,
    stock: 220,
    unit: 'sachet (250 graines)',
    category: 'Maraîchage',
    variety: 'Violet de Galmi',
    origin: 'Niger',
    imageUrl: '/placeholder.svg',
    availability: 'En stock',
    germination: '80-85%',
    harvestTime: '100-120 jours',
    plantingDepth: '1-2 cm',
    spacing: '20 cm x 10 cm',
    soilType: 'Sol limoneux, riche en matière organique',
    watering: 'Régulier, irrigation recommandée en saison sèche',
    yield: '18-25 tonnes/hectare',
    features: ['Bonne conservation', 'Saveur prononcée', 'Bulbes violets'],
    diseases: [],
    isFeatured: true,
    isPublished: true,
  },
];

async function seedSeeds() {
  console.log(`🌱 Création de ${seeds.length} semences...\n`);

  for (const data of seeds) {
    const seed = await prisma.seed.upsert({
      where: { slug: data.slug },
      create: data,
      update: data,
    });
    console.log(`✅ Semence : ${seed.name} (id=${seed.id}, slug=${seed.slug})`);
  }

  console.log(`\n🎉 ${seeds.length} semences créées avec succès.`);
}

seedSeeds()
  .catch((e) => {
    console.error('❌ Erreur lors du seed des semences :', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
